# Generated by Django 4.2.11 on 2024-07-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comapny_name', models.CharField(max_length=50)),
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_about', models.TextField(max_length=255)),
                ('website_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('job_role_name', models.CharField(max_length=50)),
                ('job_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_role_desc', models.TextField(max_length=255)),
                ('job_role_location', models.CharField(max_length=50)),
                ('job_role_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_role_qualifications', models.CharField(max_length=50)),
                ('job_role_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('INT', 'Internship')], max_length=3)),
                ('job_role_mode', models.CharField(choices=[('R', 'Remote'), ('H', 'Hybrid'), ('IP', 'In Person')], max_length=2)),
                ('job_role_posted', models.DateTimeField()),
                ('job_role_deadline', models.DateTimeField()),
                ('job_role_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobPortalApp.company')),
            ],
        ),
    ]
