# Generated by Django 4.2.11 on 2024-07-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='job_role_skills',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'JavaScript'), ('React', 'React'), ('SQL', 'SQL'), ('AWS', 'AWS'), ('Machine Learning', 'Machine Learning'), ('Data Analysis', 'Data Analysis')], default=None, max_length=50),
        ),
    ]
