# Generated by Django 4.2.11 on 2024-07-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0002_jobrole_job_role_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job_role_skills',
            field=models.TextField(max_length=50),
        ),
    ]
