# Generated by Django 4.2.11 on 2024-07-23 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0003_alter_jobrole_job_role_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='company_password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='job_role_posted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
