# Generated by Django 4.2.11 on 2024-07-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0004_company_company_email_company_company_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='comapny_name',
            new_name='company_name',
        ),
    ]
