# Generated by Django 4.2 on 2024-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0005_rename_comapny_name_company_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_resume', models.FileField(upload_to='resumes/')),
                ('user_desc', models.TextField(max_length=255)),
                ('user_education', models.TextField(max_length=255)),
                ('user_skills', models.ManyToManyField(related_name='users', to='JobPortalApp.skills')),
            ],
        ),
    ]
