# Generated by Django 4.2 on 2024-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0006_skills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_skills',
        ),
        migrations.AddField(
            model_name='user',
            name='user_skills',
            field=models.CharField(default='', max_length=100),
        ),
    ]
